@startuml
title 基于GitHub的实验管理平台--注册用例的顺序图
actor 用户
用户 -> 注册窗口: 填写注册信息
注册窗口 ->users:查询用户名密码长度是否正确
alt 用户名密码长度正确
    users->登录窗口:跳转到选择学期界面
    登录窗口->用户:跳转到主界面
else 用户名或密码长度错误
    users->用户:提示用户名或密码长度错误
end
@enduml