@startuml
title 基于GitHub的实验管理平台--登录用例的顺序图
actor 用户
用户 -> 登录窗口: 填写登录信息
登录窗口 ->users:查询用户名密码是否正确
alt 用户名密码正确
    users->登录窗口:跳转到学期选择界面
    登录窗口->用户:跳转到主界面
else 用户名或密码错误
    users->用户:提示用户名或密码错误
end
@enduml