@startuml
class 超级管理员 {
		-String ID
	 	-String username
	 	-String password
		-String Sex
		__public方法__
	 	+维护图书管理员信息()
		+维护系统信息()
		__成员方法__
		+ setUsername()
 		+ setPassword()
		+ getUsername()
 		+ getPassword()
 		
	}
class 图书管理员 {
		-String ID
	 	-String username
	 	-String password
		-String Sex
		__public方法__
		+查询图书()
		+添加图书()
		+删除图书()
		+修改图书()
		+维护图书()
		+归还图书()
		+借还图书()
		+维护读者()
		__成员方法__
		
        + setUsername()
 		+ setPassword()
		+ getUsername()
 		+ getPassword()
 		
	}   
    class 借阅者 {
        -String ID
	 	-String username
	 	-String password
		-String Sex
		__public方法__
		+查询借阅信息()
		+预订图书()
		+取消预订()
		__成员方法__
		+ setUsername()
 		+ setPassword()
		+ getUsername()
 		+ getPassword()
 		
	}
	class 游客 {
		__public方法__
		+查询图书()
	}
	class 图书 {
		__ 私有属性 __
	 	-String BookName
	 	-String ISBN
	 	-Int Total
	 	-Int Stock
	 	-Double Price
	 	-String Publish
	 	-String Abstract
	 	-String Autor
	}
	class 预订书籍{
    +String  ISBN
    +String  ID
    +Data  date
    +新增预订信息()
    +删除预订信息()
    +更新预订信息()
    +查询预订信息()
}
class 借阅书籍{
    +String  ISBN
    +String  ID
    +Data  BorrowDate
    +Data  BackDate
    +查询书籍()
    +借阅书籍()
    +归还书籍()
}
class 借书记录 {
		__ 私有属性 __
	 	-String UserName
	 	-String ISBN
	 	-Date BorrowDate
	 	-Data  BackDate
	}
	
	图书管理员 <|-- 超级管理员 : 维护图书管理员信息
	游客 <|-- 借阅者 : 注册登录
	图书管理员 "1" -- "N" 借阅者 : 维护读者信息
	图书管理员 "1" -- "N" 图书 : 维护图书
	借书记录 "1" o-- "1" 图书 : 一一对应
	借书记录 "N" -- "1" 图书管理员 : 登记和归还
	借阅者 "1" -- "N" 预订书籍 : 预定书籍
	借阅者 "1" -- "N" 借阅书籍 : 借阅书籍
	借阅者 "1" *-- "N" 借书记录 : 借书和还书
	预订书籍 "1" o-- "1" 图书 : 一一对应
	借阅书籍 "1" o-- "1" 图书 : 一一对应
	游客 "N" -- "N" 图书 : 查看书籍
@enduml
